[mqtt]
####################################
####################################
# SHOULD NEVER NEED TO CHANGE THESE
HOST = "localhost"
REMOTE_HOST = "192.168.1.101"
PORT = 1883
CTD_DATA_TOPIC = "rift-ox/ctdmon/ctddata"
CTD_CMD_TOPIC = "rift-ox/ctdmon/cmd"
WINCH_CMD_TOPIC = "rift-ox/winch/cmd"
WINCH_LATCH_TOPIC = "rift-ox/winch/latch"
WINCH_PAUSE_TOPIC = "rift-ox/winch/pause"

# AWS IoT parameters
# Changing these will requies changes at AWS

# AWS Account IoT Endpoint (not static IPs)
# AWS_ENDPOINT = "aobtoeln2b95i-ats.iot.us-east-2.amazonaws.com"

# AWS Custom domain that forwards to a network load balancer (NLB)
# and two static IPs with listening targer of VPC Endpoint of AWS IoT service
# The staic IPs have been whitelisted in BlueSky firewalls
AWS_ENDPOINT = "iot.rift-ox.net"
AWS_PORT = 8883
AWS_ROOT_CA_FILE = '~/aws/root-CA.crt'
AWS_CERT_FILE = '~/aws/rift-ox.cert.pem'
AWS_PRIV_KEY_FILE = '~/aws/rift-ox.private.key'
AWS_DATA_TOPIC = "rift-ox/ctd/data"

# Note client_id MUST start with 'rift-ox-'
AWS_RIFT_OX_CLIENT_ID = 'rift-ox-1'
####################################
####################################

[winch]
# DEPTHS & ALTITUDE are in meters
STAGING_DEPTH = 5

# HOW DEEP DO YOU WANT TO GO (meters)?
MAX_DEPTH = 300

# MIN_ALTITUDE MUST be meters <=100m
# NEGAITVE values effectively disable altimeter checking
MIN_ALTITUDE = -90

# TO HELP COMPENSATE for OVER SHOOT at ALL STOPPING DEPTHS (meters)
DEPTH_OFFSET_M = 0.1

# PAUSE TIMEOUTs in SECS. USED FOR STAGING and BOTTLE FIRING PAUSE_DEPTHS
PAUSE_DURATION_SECS = 300
BOTTLE_PAUSE_DURATION_SECS = 300

# Parking parameters in milliseconds
PARKING_DOWNCAST_MS = 450
PARKING_UPCAST_INC_MS = 500
UNPARKING_UPCAST_MS = 1000
UNPARKING_DOWNCAST_MS = 1200

# Leave in UpStaged state at ASTAGING_DEPTH if NO_PARKING == true
NO_PARKING = false

# For PAYOUT DEPTH CALCULATION
SEA_CABLE_DIAMETER_INCH = 0.123
SHEAVE_RADIUS_INCH = 2.5

[rift-ox-pi]
# overall OnLogic Pi system paramneters


# IF REALTIME_CTD is 'true', winctl will output a log message if no CTD data is received in ~60 secs
REALTIME_CTD = false

# FOR SIMULATION TESTING. LEAVE THIS 'false'
SIMULATION = false

# set to 'true' to enable the DATA RELAY TO AWS IoT
SKIP_AWS = false

# DIRs are relative to rift-ox homedir
LOG_DIR = 'dev/logs'
PAYOUT_FN = 'payouts'

# OnLogic serial ports fort C&C
DIO_PORT = '/dev/ttyACM0'
INVERTER_CMD_PORT = '/dev/ttyACM1'

#############################
# OUTPUT PINS: DO NOT CHANGE UNLESS GPIO CONNECTIONS 
# OF WINCH CTL LINES HAVE CHANGED
DIO_MOTOR_STOP_GROUP = 0
DIO_MOTOR_STOP_PIN = 0
DIO_DOWNCAST_GROUP = 0
DIO_DOWNCAST_PIN = 1
DIO_UPCAST_GROUP = 0
DIO_UPCAST_PIN = 2
DIO_LATCH_RELEASE_GROUP = 0
DIO_LATCH_RELEASE_PIN = 3
#############################

#############################
# INPUT PINS: DO NOT CHANGE UNLESS GPIO CONNECTIONS 
# OF WINCH CTL LINES HAVE CHANGED
DIO_PAYOUT1_SENSOR_GROUP = 0
DIO_PAYOUT1_SENSOR_PIN = 0
DIO_PAYOUT2_SENSOR_GROUP = 0
DIO_PAYOUT2_SENSOR_PIN = 1
DIO_LATCH_SENSOR_GROUP = 0
DIO_LATCH_SENSOR_PIN = 2
#############################

[bottles]
# file is in ./config dir
PAUSE_DEPTHS_FN = 'pause_depths.toml'
