[mqtt]
HOST = "localhost"
PORT = 1883
CTD_DATA_TOPIC = "rift-ox/ctdmon/ctddata"
WINCH_CMD_TOPIC = "rift-ox/winch/cmd"
WINCH_PAYOUTDATA_TOPIC = "rift-ox/winch/payoutdata"
WINCH_LATCH_TOPIC = "rift-ox/winch/latch"
WINCH_PAUSE_TOPIC = "rift-ox/winch/pause"

[winch]
# DEPTHS & ALTITUDE are in meters
STAGING_DEPTH = 4
MAX_DEPTH = 740
MIN_ALTITUDE = 5
STATIONARY_MAX_DIFF = 0.1
# PAUSE TIMEOUT in MINUTES
PAUSE_TIMEOUT = 15
PARKING_DOWNCAST_1_MS = 750
PARKING_UPCAST_MS = 200
PARKING_DOWNCAST_2_MS = 300

[rift-ox-pi]
# DIRs are relative to rift-ox homedir
OPS_DIR = 'dev/rift-ox/dev/ops'
PAYOUT_FN = 'payouts'
PAUSE_DURATION_SECS = 30
DIO_PORT = '/dev/ttyACM0'
DIO_DOWNCAST_GROUP = 0
DIO_DOWNCAST_PIN = 1
DIO_UPCAST_GROUP = 0
DIO_UPCAST_PIN = 3
DIO_MOTOR_PWR_GROUP = 2
DIO_MOTOR_PWR_PIN = 1
DIO_MOTOR_STOP_GROUP = 2
DIO_MOTOR_STOP_PIN = 2
DIO_LATCH_RELEASE_GROUP = 2
DIO_LATCH_RELEASE_PIN = 3
DIO_PAYOUT1_SENSOR_GROUP = 0
DIO_PAYOUT1_SENSOR_PIN = 0
DIO_PAYOUT2_SENSOR_GROUP = 0
DIO_PAYOUT2_SENSOR_PIN = 1
DIO_LATCH_SENSOR_GROUP = 0
DIO_LATCH_SENSOR_PIN = 2
REATIME_CTD = true
SIMULATION = true