[mqtt]
HOST = "localhost"
REMOTE_HOST = "192.168.1.101"
PORT = 1883
CTD_DATA_TOPIC = "rift-ox/ctdmon/ctddata"
WINCH_CMD_TOPIC = "rift-ox/winch/cmd"
# WINCH_PAYOUTDATA_TOPIC = "rift-ox/winch/payoutdata"
WINCH_LATCH_TOPIC = "rift-ox/winch/latch"
WINCH_PAUSE_TOPIC = "rift-ox/winch/pause"

[winch]
# DEPTHS & ALTITUDE are in meters
STAGING_DEPTH = 4
MAX_DEPTH = 100
# MIN_ALTITUDE MUST be <=100m
MIN_ALTITUDE = 10
# PAUSE TIMEOUT in SECS
PAUSE_DURATION_SECS = 120
PARKING_DOWNCAST_MS = 450
PARKING_UPCAST_INC_MS = 500
UNPARKING_UPCAST_MS = 1000
UNPARKING_DOWNCAST_MS = 1200
# Leave in UpStaged state if NO_PARKING is true
NO_PARKING = true
SEA_CABLE_DIAMETER_INCH = 0.123
SHEAVE_RADIUS_INCH = 2.5

[rift-ox-pi]
REALTIME_CTD = false
SIMULATION = false
# DIRs are relative to rift-ox homedir
OPS_DIR = 'dev/ops'
PAYOUT_FN = 'payouts'
DIO_PORT = '/dev/ttyACM0'
# OUTPUT PINS
DIO_MOTOR_STOP_GROUP = 0
DIO_MOTOR_STOP_PIN = 0
DIO_DOWNCAST_GROUP = 0
DIO_DOWNCAST_PIN = 1
DIO_UPCAST_GROUP = 0
DIO_UPCAST_PIN = 2
DIO_LATCH_RELEASE_GROUP = 0
DIO_LATCH_RELEASE_PIN = 3
DIO_KILL33_GROUP = 2
DIO_KILL33_PIN = 0
# INPUT PINS
DIO_PAYOUT1_SENSOR_GROUP = 0
DIO_PAYOUT1_SENSOR_PIN = 0
DIO_PAYOUT2_SENSOR_GROUP = 0
DIO_PAYOUT2_SENSOR_PIN = 1
DIO_LATCH_SENSOR_GROUP = 0
DIO_LATCH_SENSOR_PIN = 2

[bottles]
# file is in OPS_DIR
PAUSE_DEPTHS_FN = 'pause_depths.toml'
